"""add_created_at_to_users

Revision ID: 4577990ee1b3
Revises: 6cb1828fea47
Create Date: 2025-05-01 21:05:14.008678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4577990ee1b3'
down_revision: Union[str, None] = '6cb1828fea47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_column('users', 'address')
    op.drop_column('users', 'current_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
