"""add_packages_table

Revision ID: 82dd26edbf60
Revises: dda1dbdb3768
Create Date: 2025-05-01 21:51:26.116964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82dd26edbf60'
down_revision: Union[str, None] = 'dda1dbdb3768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('destination_pvz', sa.String(), nullable=True))
    op.drop_column('packages', 'updated_at')
    op.drop_column('packages', 'current_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('current_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('packages', 'destination_pvz')
    # ### end Alembic commands ###
